name: "Datadog STS"

description: |
  This action exchanges the workflow's identity token for
  Datadog credentials according to a target trust policy.

inputs:
  domain:
    description: The domain of the Datadog STS instance to use to federate.
    default: webhooks.build.datadoghq.com

  policy:
    description: The name of the trust policy to use.
    required: true

  audience:
    description: The audience value for the OIDC token. Must match the audience configured in your dd-sts policy.
    default: rapid-seceng-sit

outputs:
  api_key:
    description: A Datadog API key.
    value: ${{ steps.dd-sts.outputs.api_key }}

  app_key:
    description: A Datadog application key.
    value: ${{ steps.dd-sts.outputs.app_key }}

  app_key_expiration_timestamp:
    description: The expiration timestamp of the application key.
    value: ${{ steps.dd-sts.outputs.app_key_expiration_timestamp }}

runs:
  using: "node20"
  main: "index.js"
  post: "post.js"
  post-if: success() || failure() # ensures the cleanup runs whether the workflow succeeds or fails, but only if an application key was actually returned
